apiVersion: v1
kind: Service
metadata:
  name: reporting-events-processor-svc
  labels:
    app.kubernetes.io/name: reporting-events-processor-svc
spec:
  ports:
  - port: 80
    targetPort: 8084
    name: http
  selector:
    app.kubernetes.io/name: reporting-events-processor-svc
