apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-hub-bop-api-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reporting-hub-bop-api-svc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reporting-hub-bop-api-svc
    spec:
      containers:
      - name: app
        image: ghcr.io/mojaloop/reporting-hub-bop-api-svc:v1.0.18
        ports:
        - containerPort: 8084
        env:
          - name: CLDB_HOST
            value: '{{ include "common.backends.reportingDB.host" . }}'
          - name: CLDB_PORT
            value: '{{ include "common.backends.reportingDB.port" . }}'
          - name: CLDB_NAME
            value: '{{ include "common.backends.reportingDB.database" . }}'
          - name: CLDB_USER
            value: '{{ include "common.backends.reportingDB.user" . }}'
          - name: CLDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: '{{ include "common.backends.reportingDB.secret.name" . }}'
                key: '{{ include "common.backends.reportingDB.secret.key" . }}'
          - name: CENTRAL_LEDGER_DB_URL
            value: mysql://$(CLDB_USER):$(CLDB_PASSWORD)@$(CLDB_HOST):$(CLDB_PORT)/$(CLDB_NAME)
          # Event Store
          - name: EVENT_DB_HOST
            value: '{{ include "common.backends.reportingEventsDB.host" . }}'
          - name: EVENT_DB_PORT
            value: '{{ include "common.backends.reportingEventsDB.port" . }}'
          - name: EVENT_DB_NAME
            value: '{{ include "common.backends.reportingEventsDB.database" . }}'
          - name: EVENT_DB_USER
            value: '{{ include "common.backends.reportingEventsDB.user" . }}'
          - name: EVENT_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: '{{ include "common.backends.reportingEventsDB.secret.name" . }}'
                key: '{{ include "common.backends.reportingEventsDB.secret.key" . }}'
          - name: EVENT_STORE_DB_URL
            value: mongodb://$(EVENT_DB_USER):$(EVENT_DB_PASSWORD)@$(EVENT_DB_HOST):$(EVENT_DB_PORT)/$(EVENT_DB_NAME)
          {{- if .Values.auth }}
          - name: ORY_KETO_READ_URL
            value: '{{ include "common.backends.keto.readURL" . }}'
          {{- end }}
