apiVersion: v1
kind: Service
metadata:
  name: reporting-hub-bop-api-svc
  labels:
    app.kubernetes.io/name: reporting-hub-bop-api-svc
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app.kubernetes.io/name: reporting-hub-bop-api-svc
